language: node_js
node_js:
  - "4.1"
  - "0.12"
sudo: required
#before_install:
#  - "npm install npm@$NPM_VERSION -g"
after_success:
  - "./node_modules/coveralls/bin/coveralls.js < reports/coverage/lcov.info"